import gridCells from '../grid-cells'

describe('gridCells()', () => {
  test('should return expected cell data', () => {
    expect(gridCells({ width: 100, height: 100, rows: 10, cols: 5 })).toEqual({
      width: 20,
      height: 10,
      cells: [
        {
          col: 0,
          row: 0,
          x: 0,
          y: 0,
        },
        {
          col: 1,
          row: 0,
          x: 20,
          y: 0,
        },
        {
          col: 2,
          row: 0,
          x: 40,
          y: 0,
        },
        {
          col: 3,
          row: 0,
          x: 60,
          y: 0,
        },
        {
          col: 4,
          row: 0,
          x: 80,
          y: 0,
        },
        {
          col: 0,
          row: 1,
          x: 0,
          y: 10,
        },
        {
          col: 1,
          row: 1,
          x: 20,
          y: 10,
        },
        {
          col: 2,
          row: 1,
          x: 40,
          y: 10,
        },
        {
          col: 3,
          row: 1,
          x: 60,
          y: 10,
        },
        {
          col: 4,
          row: 1,
          x: 80,
          y: 10,
        },
        {
          col: 0,
          row: 2,
          x: 0,
          y: 20,
        },
        {
          col: 1,
          row: 2,
          x: 20,
          y: 20,
        },
        {
          col: 2,
          row: 2,
          x: 40,
          y: 20,
        },
        {
          col: 3,
          row: 2,
          x: 60,
          y: 20,
        },
        {
          col: 4,
          row: 2,
          x: 80,
          y: 20,
        },
        {
          col: 0,
          row: 3,
          x: 0,
          y: 30,
        },
        {
          col: 1,
          row: 3,
          x: 20,
          y: 30,
        },
        {
          col: 2,
          row: 3,
          x: 40,
          y: 30,
        },
        {
          col: 3,
          row: 3,
          x: 60,
          y: 30,
        },
        {
          col: 4,
          row: 3,
          x: 80,
          y: 30,
        },
        {
          col: 0,
          row: 4,
          x: 0,
          y: 40,
        },
        {
          col: 1,
          row: 4,
          x: 20,
          y: 40,
        },
        {
          col: 2,
          row: 4,
          x: 40,
          y: 40,
        },
        {
          col: 3,
          row: 4,
          x: 60,
          y: 40,
        },
        {
          col: 4,
          row: 4,
          x: 80,
          y: 40,
        },
        {
          col: 0,
          row: 5,
          x: 0,
          y: 50,
        },
        {
          col: 1,
          row: 5,
          x: 20,
          y: 50,
        },
        {
          col: 2,
          row: 5,
          x: 40,
          y: 50,
        },
        {
          col: 3,
          row: 5,
          x: 60,
          y: 50,
        },
        {
          col: 4,
          row: 5,
          x: 80,
          y: 50,
        },
        {
          col: 0,
          row: 6,
          x: 0,
          y: 60,
        },
        {
          col: 1,
          row: 6,
          x: 20,
          y: 60,
        },
        {
          col: 2,
          row: 6,
          x: 40,
          y: 60,
        },
        {
          col: 3,
          row: 6,
          x: 60,
          y: 60,
        },
        {
          col: 4,
          row: 6,
          x: 80,
          y: 60,
        },
        {
          col: 0,
          row: 7,
          x: 0,
          y: 70,
        },
        {
          col: 1,
          row: 7,
          x: 20,
          y: 70,
        },
        {
          col: 2,
          row: 7,
          x: 40,
          y: 70,
        },
        {
          col: 3,
          row: 7,
          x: 60,
          y: 70,
        },
        {
          col: 4,
          row: 7,
          x: 80,
          y: 70,
        },
        {
          col: 0,
          row: 8,
          x: 0,
          y: 80,
        },
        {
          col: 1,
          row: 8,
          x: 20,
          y: 80,
        },
        {
          col: 2,
          row: 8,
          x: 40,
          y: 80,
        },
        {
          col: 3,
          row: 8,
          x: 60,
          y: 80,
        },
        {
          col: 4,
          row: 8,
          x: 80,
          y: 80,
        },
        {
          col: 0,
          row: 9,
          x: 0,
          y: 90,
        },
        {
          col: 1,
          row: 9,
          x: 20,
          y: 90,
        },
        {
          col: 2,
          row: 9,
          x: 40,
          y: 90,
        },
        {
          col: 3,
          row: 9,
          x: 60,
          y: 90,
        },
        {
          col: 4,
          row: 9,
          x: 80,
          y: 90,
        },
      ],
    })
  })
})
